branch-defaults:
  default:
    environment: JeeServer-Api-Stat
environment-defaults:
  JeeServer-Api-Stat:
    branch: null
    repository: null
global:
  application_name: JEE-API-STAT
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux 2/3.0.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
